# Site settings
title: Nidhi Ranjan
description: Software Engineer
lang: en-US
timezone: Asia/India
image: assets/img/ogp.png # This image used for Open Graph more info https://ogp.me/
repo: https://github.com/piharpi/mahendrata.now.sh
mode: dark # default theme "dark" | "light"

# Profile settings
author:
  name: Nidhi Ranjan
  bio: Software Engineer
  username: Nidhi Ranjan
  email: nidhi.nitg@gmail.com
  avatar: /assets/img/avatar.jpg

linkedin_username: nidran
github_username: nidran
twitter_username: nidran
# Url settings
url:
baseurl:
permalink: /:title/
google_analytics:
fb_appid:

# Collection setting
collections:
  posts:
    output: true

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: post
      comments: false

# Jekyll Compose default front matter
jekyll_compose:
  post_default_front_matter:
    modified:
    tags: []
    description:
  draft_default_front_matter:
    modified:
    tags: []
    description:

# Build settings
sass:
  style: compressed

include:
  - _redirects
  - .htaccess

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CHANGELOG.md
  - README.md
  - node_modules
  - CODE_OF_CONDUCT.md

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sass-converter
  - jekyll-sitemap
  - jekyll-postfiles
